# echo -e ${colorBlack} Black ${colorDarkGray} Dark Gray ${colorBlue} Blue ${colorLightBlue} Light Blue ${colorGreen} Green ${colorLightGreen} Light Green ${colorCyan} Cyan ${colorLightCyan} Light Cyan ${colorRed} Red ${colorLightRed} Light Red ${colorPurple} Purple ${colorLightPurple} Light Purple ${colorBrownOrange} Brown/Orange ${colorYellow} Yellow ${colorLightGray} Light Gray ${colorWhite} White ${colorReset}
export colorBlack='\e[0;30m'
export colorDarkGray='\e[1;30m'
export colorBlue='\e[0;34m'
export colorLightBlue='\e[1;34m'
export colorGreen='\e[0;32m'
export colorLightGreen='\e[1;32m'
export colorCyan='\e[0;36m'
export colorLightCyan='\e[1;36m'
export colorRed='\e[0;31m'
export colorLightRed='\e[1;31m'
export colorPurple='\e[0;35m'
export colorLightPurple='\e[1;35m'
export colorBrownOrange='\e[0;33m'
export colorYellow='\e[1;33m'
export colorLightGray='\e[0;37m'
export colorWhite='\e[1;37m'
export colorReset='\e[0m'
